// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwmc2T-97iyzfGDkClUB0D33Bu9rbzCT4',
    appId: '1:786664094517:web:2d80b91323384bfa12ea7c',
    messagingSenderId: '786664094517',
    projectId: 'weather-app-c8565',
    authDomain: 'weather-app-c8565.firebaseapp.com',
    storageBucket: 'weather-app-c8565.appspot.com',
    measurementId: 'G-N8MK964WLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxBVGTMZBa2xhJNxxFQedUzJ16kZD4pFQ',
    appId: '1:786664094517:android:6479b46aca51530d12ea7c',
    messagingSenderId: '786664094517',
    projectId: 'weather-app-c8565',
    storageBucket: 'weather-app-c8565.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyrtc9BJmRHg3vjo3u4r3EVpN8Y3P5yoA',
    appId: '1:786664094517:ios:536722185cbc795912ea7c',
    messagingSenderId: '786664094517',
    projectId: 'weather-app-c8565',
    storageBucket: 'weather-app-c8565.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyrtc9BJmRHg3vjo3u4r3EVpN8Y3P5yoA',
    appId: '1:786664094517:ios:6065c9a7dbe075e812ea7c',
    messagingSenderId: '786664094517',
    projectId: 'weather-app-c8565',
    storageBucket: 'weather-app-c8565.appspot.com',
    iosBundleId: 'com.example.weatherApp.RunnerTests',
  );
}
